FROM ubuntu:focal

#  Add utility packages to image
RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get -q install -y \
    -o Dpkg::Options::="--force-confnew"  --no-install-recommends \
    apt-utils ca-certificates locales gnupg2 tzdata vim-tiny curl wget unzip lsb-release sudo git git-lfs && \
    apt-get -q autoremove && \
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && \
    rm -f /var/cache/apt/*.bin && \
    locale-gen en_US.UTF-8 && \
    echo "dash dash/sh boolean false" | debconf-set-selections && \
    dpkg-reconfigure -f noninteractive dash

# Install Jenkins agent.  See https://hub.docker.com/r/jenkins/agent & https://github.com/jenkinsci/docker-inbound-agent
ARG JENKINS_AGENT_VER=4.5
RUN curl --create-dirs -fsSLo /usr/share/jenkins/agent.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${JENKINS_AGENT_VER}/remoting-${JENKINS_AGENT_VER}.jar \
  && chmod 755 /usr/share/jenkins \
  && chmod 644 /usr/share/jenkins/agent.jar \
  && ln -sf /usr/share/jenkins/agent.jar /usr/share/jenkins/slave.jar \
  && curl -fsSLo /usr/local/bin/jenkins-agent https://raw.githubusercontent.com/jenkinsci/docker-inbound-agent/master/jenkins-agent \
  && chmod 755 /usr/local/bin/jenkins-agent \
  && ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave


ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

## Install Nodejs
ARG NODEJS_VERSION=12.20.1
RUN curl -sL https://deb.nodesource.com/setup_${NODEJS_VERSION}.x | bash -

# Install Postgres repo
ARG POSTGRES_VERSION=11
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" \
     > /etc/apt/sources.list.d/pgdg.list && \
    wget -q --no-check-certificate --no-cookies -O - \
    https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# Install google chrome repo
RUN wget -q --no-check-certificate --no-cookies -O - \
    https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
    > /etc/apt/sources.list.d/google.list

# Install  packages for our build environment.
RUN apt-get -q update && \
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y \
    -o Dpkg::Options::="--force-confnew"  --no-install-recommends \
    openjdk-11-jdk jq maven python3  python3-pip python3-setuptools python3-wheel python3-yaml python3-requests python3-sh nodejs \
    postgresql-client-${POSTGRES_VERSION} xvfb libgtk2.0-0 libxtst6 libxss1 libgconf-2-4 libnss3 \
    libnspr4 libasound2 google-chrome-stable libaio1 zip && \
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && \
    rm -f /var/cache/apt/*.bin && \
    rm -f /tmp/node.sh && \
    rm -f /etc/apt/sources.list.d/google.list

#RUN npm install -g raml2html@3.0.1 && \
#  npm install -g npm-snapshot

ARG YARN_VERSION=1.22.5-1
RUN wget -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    sh -c 'echo "deb https://dl.yarnpkg.com/debian/ stable main" \
    >> /etc/apt/sources.list.d/yarn.list' && \
    apt-get -q update && apt-get install -y yarn=${YARN_VERSION}
#    yarn config set registry https://repository.folio.org/repository/npm-ci-all && \
#    yarn global add @folio/stripes-cli --prefix /usr/local

# Install Docker cli
ARG DOCKER_VERSION=19.03.9
RUN wget -q --no-check-certificate --no-cookies \
    https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz \
    -O /tmp/docker.tgz && \
    cd /tmp && tar zxvf docker.tgz && \
    mv /tmp/docker/* /usr/local/bin/ && \
    rm -rf /tmp/docker*

# Install AWS v2 cli tools
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
  unzip ./awscliv2.zip -d /tmp && /tmp/aws/install && \
  rm -rf /tmp/aws && rm ./awscliv2.zip

# Ansible (from pip)
ARG ANSIBLE_VERSION=2.9.13
RUN pip3 install boto && \
    pip3 install boto3 && \
    pip3 install jmespath && \
    pip3 install ansible==${ANSIBLE_VERSION}


# docker build '--build-arg' and their FOLIO CI defaults
ARG user=jenkins
ARG user_email=folio-jenkins@indexdata.com
ARG group=jenkins
ARG uid=497
ARG gid=1000
ARG docker_gid=496
ARG docker_user=jenkins

ARG JENKINS_AGENT_HOME=/home/${user}
ARG JENKINS_AGENT_WORKDIR=/home/${user}/agent

RUN groupadd -g ${gid} ${group} \
    && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}" \
    && groupadd -g ${docker_gid} docker \
    && usermod -a -G docker ${docker_user} \
    && bash -c "echo '${user} ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/folio" \
    && bash -c "echo '[user]' > ${JENKINS_AGENT_HOME}/.gitconfig" \ && bash -c "echo '  email = ${user_email}' >> ${JENKINS_AGENT_HOME}/.gitconfig" \ && bash -c "echo '  name  = ${user}' >> ${JENKINS_AGENT_HOME}/.gitconfig" \ && yarn config set @folio:registry https://repository.folio.org/repository/npm-folio/ \
    && mv /usr/local/share/.yarnrc ${JENKINS_AGENT_HOME} \
    && chown -R ${user}.${group} ${JENKINS_AGENT_HOME}

# Run as user, $user,to install sdkman for Gradle
RUN su - ${user} -s /bin/bash -c 'curl -s "https://get.sdkman.io" | bash \
    && source "/home/jenkins/.sdkman/bin/sdkman-init.sh" \
    && sdk install gradle 4.9'

USER ${user}
RUN mkdir /home/${user}/.jenkins && mkdir -p ${JENKINS_AGENT_WORKDIR}

ENV JENKINS_AGENT_HOME=${JENKINS_AGENT_HOME}
ENV JENKINS_AGENT_WORKDIR=${JENKINS_AGENT_WORKDIR}
ENV AGENT_WORKDIR=${JENKINS_AGENT_WORKDIR}

VOLUME "${JENKINS_AGENT_HOME}/.jenkins" "${JENKINS_AGENT_WORKDIR}" "/tmp" "/run" "/var/run" "/var/run/docker.sock"
WORKDIR "${JENKINS_AGENT_HOME}"

#ENTRYPOINT ["jenkins-agent"]
ENTRYPOINT ["/bin/bash"]

