FROM fabric8/java-alpine-openjdk8-jre:latest

ENV JAVA_APP_DIR /usr/verticles
RUN mv /deployments $JAVA_APP_DIR

# Create user/group 'folio'
RUN addgroup folio && \
    adduser -H -h $JAVA_APP_DIR -G folio -D folio && \
    chown -R folio.folio $JAVA_APP_DIR

# Run as this user
USER folio
WORKDIR $JAVA_APP_DIR

ENTRYPOINT [ "./run-java.sh" ]
